<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>CMakeCache.txt</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>CMake Cache</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignation</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>assignation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.cache.cmake</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.argument-separator.cmake</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.cache.cmake</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.cmake</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.cmake</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z0-9_\-\d]+)(:)(STRING|FILE|FILEPATH|BOOL|INTERNAL|STATIC)(\=)(.*)</string>
			<key>name</key>
			<string>variable.cmake</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//|\#)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.cmake</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.cmake</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.double-slash.cmake</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\#</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.cmake</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.sign-line.cmake</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cache.cmake</string>
	<key>uuid</key>
	<string>B4264EAE-087F-403D-A84B-C4B16EB885D3</string>
</dict>
</plist>
