<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asn</string>
	</array>
	<key>name</key>
	<string>ASN</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>([\w\-]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.asn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(BEGIN)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.asn</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#builtin_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtin_operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtin_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#base_type</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>base_type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.asn</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.asn</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.type.asn</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>type definition</string>
					<key>match</key>
					<string>^\s*([\w\-]+)\s*(::=)\s+(\w+)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(::=)</string>
					<key>name</key>
					<string>keyword.operator.asn</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>bitstring</string>
					<key>match</key>
					<string>\'[01]*\'B</string>
					<key>name</key>
					<string>string.quoted.single.asn</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>octetstring</string>
					<key>match</key>
					<string>\'([a-fA-F0-9][a-fA-F0-9])*\'O</string>
					<key>name</key>
					<string>string.quoted.single.asn</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>hexstring</string>
					<key>match</key>
					<string>\'[a-fA-F0-9]*\'H</string>
					<key>name</key>
					<string>string.quoted.single.asn</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>string</string>
					<key>match</key>
					<string>\".*\"</string>
					<key>name</key>
					<string>string.quoted.double.asn</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>numeric</string>
					<key>match</key>
					<string>\b[\d+|infinity|\-infinity]+\b</string>
					<key>name</key>
					<string>constant.numeric.asn</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>variable definition</string>
					<key>match</key>
					<string>([\w\-]+)</string>
				</dict>
			</array>
		</dict>
		<key>builtin_keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.asn</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*\b(if|else|for|while|do|repeat)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.asn</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
\b(DEFAULT|OPTIONAL|DEFINITIONS|BEGIN|END|IMPORTS|EXPORTS|FROM|IMPLICIT|EXPLICIT|AUTOMATIC|
ABSENT|PRESENT|SIZE|UNIVERSAL|APPLICATION|PRIVATE|TRUE|FALSE|MIN|MAX|optional|mandatory)\b</string>
				</dict>
			</array>
		</dict>
		<key>builtin_operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.asn</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([-+*/?&lt;&gt;=])\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.asn</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([=!&gt;&lt;]=)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.asn</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(\.\.)\b</string>
				</dict>
			</array>
		</dict>
		<key>builtin_types</key>
		<dict>
			<key>match</key>
			<string>(?x) \b(ABSENT|PRESENT|SIZE|UNIVERSAL|APPLICATION|PRIVATE|INTEGER|REAL|STRING|BIT|BOOLEAN|OCTET |NULL|EMBEDDED|PDV|BMPString|IA5String|TeletexString|GeneralString|GraphicString| ISO646String|NumericString|PrintableString|T61String|UniversalString|VideotexString| VisibleString|ANY|DEFINED|OBJECT\s\+IDENTIFIER|UTF8String|CHOICE|SEQUENCE|SET|OF| ENUMERATED|CONSTRAINED|BY|WITH|COMPONENTS|CLASS|SYNTAX)\b[^-]</string>
			<key>name</key>
			<string>support.type.asn</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--.*</string>
					<key>name</key>
					<string>comment.line.double-slash.asn</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>--</string>
					<key>end</key>
					<string>--</string>
					<key>name</key>
					<string>comment.block.documentation.asn</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.asn</string>
	<key>uuid</key>
	<string>77590f80-4b89-4efa-a1a5-0ca16869cff9</string>
</dict>
</plist>
