<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>par</string>
	</array>
	<key>name</key>
	<string>PAR</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>bitstring</string>
			<key>match</key>
			<string>\'[01]*\'B</string>
			<key>name</key>
			<string>string.quoted.single.par</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>octetstring</string>
			<key>match</key>
			<string>\'([a-fA-F0-9][a-fA-F0-9])*\'O</string>
			<key>name</key>
			<string>string.quoted.single.par</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>hexstring</string>
			<key>match</key>
			<string>\'[a-fA-F0-9]*\'H</string>
			<key>name</key>
			<string>string.quoted.single.par</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>\".*\"</string>
			<key>name</key>
			<string>string.quoted.double.par</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numeric</string>
			<key>match</key>
			<string>\b[\d+]+\b</string>
			<key>name</key>
			<string>constant.numeric.par</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.par</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.variable.par</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>numeric</string>
			<key>match</key>
			<string>(\w+)\.(\w+)</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\#.*</string>
					<key>name</key>
					<string>comment.line.double-slash.par</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.par</string>
	<key>uuid</key>
	<string>77590f80-4b89-4efa-a1a5-0ca16869cff9</string>
</dict>
</plist>
