<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>ttl</string>
            <string>nt</string>
        </array>
        <key>name</key>
        <string>Turtle</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#comments</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#strings</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#base-prefix-declarations</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#string-language-suffixes</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#string-datatype-suffixes</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#relative-urls</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#xml-schema-types</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#rdf-schema-types</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#owl-types</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#qnames</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#punctuation-operators</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>base-prefix-declarations</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>@(base|prefix)</string>
                        <key>name</key>
                        <string>keyword.other.prefix.turtle</string>
                    </dict>
                </array>
            </dict>
            <key>comments</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.turtle</string>
                            </dict>
                        </dict>
                        <key>match</key>
                        <string>(#).*$\n?</string>
                        <key>name</key>
                        <string>comment.line.hash.turtle</string>
                    </dict>
                </array>
            </dict>
            <key>owl-types</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>owl:[a-zA-Z]+</string>
                        <key>name</key>
                        <string>support.type.datatype.owl.turtle</string>
                    </dict>
                </array>
            </dict>
            <key>punctuation-operators</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>(;|,|\.|\(|\)|\[|\])</string>
                        <key>name</key>
                        <string>keyword.operator.punctuation.turtle</string>
                    </dict>
                </array>
            </dict>
            <key>qnames</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>([a-zA-Z][-_a-zA-Z0-9]*)?:([_a-zA-Z][-_a-zA-Z0-9]*)?</string>
                        <key>name</key>
                        <string>entity.name.other.qname.turtle</string>
                    </dict>
                </array>
            </dict>
            <key>rdf-schema-types</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>(rdfs?:[a-zA-Z]+|(^|\s)a(\s|$))</string>
                        <key>name</key>
                        <string>support.type.datatype.rdf.schema.turtle</string>
                    </dict>
                </array>
            </dict>
            <key>relative-urls</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>&lt;</string>
                        <key>end</key>
                        <string>&gt;</string>
                        <key>name</key>
                        <string>string.quoted.other.relative.url.turtle</string>
                    </dict>
                </array>
            </dict>
            <key>string-datatype-suffixes</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>\^\^</string>
                        <key>name</key>
                        <string>keyword.operator.datatype.suffix.turtle</string>
                    </dict>
                </array>
            </dict>
            <key>string-language-suffixes</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.operator.language.suffix.turtle</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>constant.language.suffix.turtle</string>
                            </dict>
                        </dict>
                        <key>match</key>
                        <string>(?!")(@)([a-z]+(\-[a-z0-9]+)*)</string>
                    </dict>
                </array>
            </dict>
            <key>strings</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>"""</string>
                        <key>end</key>
                        <string>"""</string>
                        <key>name</key>
                        <string>string.quoted.triple.turtle</string>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>"</string>
                        <key>end</key>
                        <string>"</string>
                        <key>name</key>
                        <string>string.quoted.double.turtle</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>match</key>
                                <string>\n</string>
                                <key>name</key>
                                <string>invalid.string.newline</string>
                            </dict>
                            <dict>
                                <key>match</key>
                                <string>\\.</string>
                                <key>name</key>
                                <string>constant.character.escape.turtle</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <key>xml-schema-types</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>xsd?:[a-z][a-zA-Z]+</string>
                        <key>name</key>
                        <string>support.type.datatype.xml.schema.turtle</string>
                    </dict>
                </array>
            </dict>
        </dict>
        <key>scopeName</key>
        <string>source.turtle</string>
        <key>uuid</key>
        <string>ed843a38-56ab-4b84-84ce-251ae4077ad6</string>
    </dict>
</plist>