<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dust</string>
		<string>tl</string>
		<string>dustjs</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>DustJS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.dust_ref_name</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.dust_filter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\{([.0-9a-zA-Z_$]+)(\|[a-zA-Z]+)?\}</string>
			<key>name</key>
			<string>variable.other.dust_ref</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{!</string>
			<key>end</key>
			<string>!\}</string>
			<key>name</key>
			<string>comment.block.dustjs</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dust_section_name</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.dust_section_context</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.dust_section_params</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\{[#?^&lt;+@%]([a-zA-Z_$.0-9]+)(:[a-zA-Z_$0-9]+)?(( [a-zA-Z0-9_$]+\="?[^"]*"?)*)\}</string>
			<key>name</key>
			<string>keyword.control.dust_start_section_tag</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dust_section_name</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.dust_section_context</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.dust_section_params</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\{[#?^&lt;+@%]([a-zA-Z_$.0-9]+)(:[a-zA-Z_$0-9]+)?(( [a-zA-Z0-9_$]+\="?[^"]*"?)*)\/\}</string>
			<key>name</key>
			<string>keyword.control.dust_self_closing_section_tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{\/([.0-9a-zA-Z_$])+\}</string>
			<key>name</key>
			<string>keyword.control.dust_end_section_tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{:[a-zA-Z_$][0-9a-zA-Z_$]*\}</string>
			<key>name</key>
			<string>keyword.control.dust_Conditional</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{&gt;</string>
			<key>end</key>
			<string>\/\}</string>
			<key>name</key>
			<string>keyword.operator.dust_partial</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_context</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{&gt;</string>
			<key>end</key>
			<string>[^/]\}</string>
			<key>name</key>
			<string>invalid.illegal.dust_partial_not_self_closing</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{\~(s|n|r|lb|rb)\}</string>
			<key>name</key>
			<string>support.constant.dust_special</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>entity.name.tag.dustjs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_key</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>dust_context</key>
		<dict>
			<key>match</key>
			<string>:[a-zA-Z_$][0-9azA-Z_$]*</string>
		</dict>
		<key>dust_filter</key>
		<dict>
			<key>match</key>
			<string>\|(s|h|uc|j)</string>
		</dict>
		<key>dust_identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_path</string>
				</dict>
			</array>
		</dict>
		<key>dust_inline</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_inline_part</string>
				</dict>
			</array>
		</dict>
		<key>dust_inline_part</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_special</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_literal</string>
				</dict>
			</array>
		</dict>
		<key>dust_key</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_$][0-9a-zA-Z_$]*</string>
		</dict>
		<key>dust_literal</key>
		<dict>
			<key>match</key>
			<string>[^"]*</string>
		</dict>
		<key>dust_path</key>
		<dict>
			<key>match</key>
			<string>([.0-9a-zA-Z_$])+</string>
		</dict>
		<key>dust_special_chars</key>
		<dict>
			<key>match</key>
			<string>\{\~(s|n|r|lb|rb)\}</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.dustjs</string>
	<key>uuid</key>
	<string>766A7CF2-0901-419B-97CE-98ACA4A52079</string>
</dict>
</plist>
