<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>proto</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Protocol Buffer</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.import.protobuf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(import) (".*")</string>
			<key>name</key>
			<string>meta.import.declaration.protobuf</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(message)\s+([A-Za-z0-9_]+)\s*\{</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.message.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.message.protobuf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.message-declaration.protobuf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#any_field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(enum)\s+([A-Za-z0-9_]+)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.enum.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.enum.protobuf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.enum-declaration.protobuf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.user-defined.protobuf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.protobuf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([A-Za-z0-9_]+)\s*=\s*(\d+)\b</string>
					<key>name</key>
					<string>meta.individual-enum-definition.protobuf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#anywhere_option</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracketed_option</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(service)\s+([A-Za-z0-9_]+)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.enum.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.enum.protobuf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.service-declaration.protobuf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.rpc-definition.protobuf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.service-rpc.protobuf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.request-type.protobuf</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.returns.protobuf</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.response-type.protobuf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(rpc)\s+([A-Za-z0-9_]+)\s+\(([A-Za-z0-9_]+)\)\s*(returns)\s*\(([A-Za-z0-9_]+)\)\s*;</string>
					<key>name</key>
					<string>meta.individual-rpc-call.protobuf</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(method)\s+([A-Za-z0-9_]+)\s*\(\s*\)\s*{</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.method-modification.protobuf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.protobuf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.method-mofification.protobuf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rpc_string_attribute</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rpc_primitive_attribute</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#anywhere_option</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.package-definition.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.protobuf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(package)\s+([A-Za-z0-9.]+)\s*;</string>
			<key>name</key>
			<string>meta.package.protobuf</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extensions.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.protobufs</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.to.protobufs</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.protobufs</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(extensions)\s+(\d+)\s+(to)\s+(max|\d+);</string>
			<key>name</key>
			<string>meta.extension-specification.protobuf</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#anywhere_option</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bracketed_option</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#extend_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>any_field</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#primitive_field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#group_field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#user_defined_message_field</string>
				</dict>
			</array>
		</dict>
		<key>anywhere_option</key>
		<dict>
			<key>begin</key>
			<string>(option)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.option.protobuf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attribute</string>
				</dict>
			</array>
		</dict>
		<key>attribute</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#indiv_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_attribute</string>
				</dict>
			</array>
		</dict>
		<key>bracketed_option</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attribute</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-slash.protobuf</string>
		</dict>
		<key>extend_block</key>
		<dict>
			<key>begin</key>
			<string>\b(extend)\s+([A-Za-z0-9_]+)\s*\{</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.extend.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.message.protobuf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#any_field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>group_field</key>
		<dict>
			<key>begin</key>
			<string>(required|optional|repeated)\s+(group)\s+([A-Za-z0-9_]+)\s*=\s*(\d+)\s*{</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.occurrences.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.groups.protobuf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.primitive-field.protobuf</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.field-tag.protobuf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#any_field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>indiv_attribute</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.field-option-values.protobuf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(?([A-Za-z0-9_.]+)\)?\s*=\s*(true|false|\d+|([A-Z_]+))\b</string>
		</dict>
		<key>primitive_field</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.occurrences.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.built-in.protobuf</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.other.primitive-field.protobuf</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.field-tag.protobuf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(required|optional|repeated)\s+(((s|u)?int|s?fixed)(32|64)|string|bytes|bool)\s+(\S+)\s*=\s*(\d+)</string>
		</dict>
		<key>rpc_primitive_attribute</key>
		<dict>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.option.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.protobuf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.protobuf</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.protobuf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(option)\s+\(?([A-Za-z0-9_.]+)\)?\.([A-Za-z0-9.]+)\s*=\s*(true|false|\d+|([A-Z_]+))\b</string>
		</dict>
		<key>rpc_string_attribute</key>
		<dict>
			<key>begin</key>
			<string>(option)\s+\(?([A-Za-z0-9_.]+)\)?\.([A-Za-z0-9.]+)\s*=\s*(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.option.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.protobuf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.protobuf</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.protobuf</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.double.protobuf</string>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.protobuf</string>
				</dict>
			</dict>
		</dict>
		<key>string_attribute</key>
		<dict>
			<key>begin</key>
			<string>\(?([A-Za-z0-9_.]+)\)?\s*=\s*(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.protobuf</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.double.protobuf</string>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.protobuf</string>
				</dict>
			</dict>
		</dict>
		<key>user_defined_message_field</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.occurrences.protobuf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.user-defined-type.protobuf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.primitive-field.protobuf</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.field-tag.protobuf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(required|optional|repeated)\s+([A-Za-z.]*)\s+(\S+)\s*=\s*(\d+)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.protobuf</string>
	<key>uuid</key>
	<string>D1D0E31F-1807-408E-A184-00F4D0A2619F</string>
</dict>
</plist>
