<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>prg</string>
	</array>
	<key>name</key>
	<string>Visual FoxPro</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string3</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numericConstant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#controlKeywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#classDefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functionDefinition</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(acla|aclass|adbo|adbobjects|adat|adatabases|adir|adoc|adockstate|aerr|aerror|aeve|aevents|afie)\b)</string>
			<key>name</key>
			<string>keywords.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(afields|afon|afont|agetc|agetclass|agetf|agetfileversion|ainst|ainstance|alan|alanguage|alin)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(alines|amem|amembers|amou|amouseobj|anet|anetresources|apri|aprinters|apro|aprocinfo|asql|asqlhandles)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(asel|aselobj|asta|astackinfo|atag|ataginfo|ause|aused|avcx|avcxclasses|abs|acop|acopy|acos|addp|addproperty)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(addb|addbs|adel|adll|adlls|aele|aelement|ains|alen|alia|alias|allt|alltrim|asc|asca|ascan|ases|asessions|asin)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(asor|asort|asub|asubscript|at|at_c|atan|atc|atcc|atcl|atcline|atli|atline|avg|bar|betw|between|bint|bintoc|bind)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(bindevent|bita|bitand|bitc|bitclear|bitl|bitlshift|bitn|bitnot|bito|bitor|bitr|bitrshift|bits|bitset|bitt)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(bittest|bitx|bitxor|bof|ctob|ctobin|cand|candidate|caps|capslock|cast|cdow|cdx|ceil|ceiling|chr|chrs|chrsaw)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(chrt|chrtran|chrtranc|clearr|clearresultset|cmon|cmonth|cnt|cntb|cntbar|cntp|cntpad|coma|comarray|comc)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(comclassinfo|comr|comreturnerror|comp|compobj|comprop|cos|count|cpco|cpconvert|cpcu|cpcurrent|cpdb|cpdbf)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(createb|createbinary|create|createobject|createobjectex|createof|createoffline|ctod|ctot|curd|curdir|cursorg)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(cursorgetprop|cursors|cursorsetprop|cursortox|cursortoxml|curv|curval|dbal|dbalias|dbge|dbgetprop|dbse|dbsetprop)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(dbus|dbused|ddeab|ddeaborttrans|ddead|ddeadvise|ddeen|ddeenabled|ddeex|ddeexecute|ddei|ddeinitiate|ddel|ddelasterror)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(ddep|ddepoke|dder|dderequest|ddes|ddesetoption|ddesets|ddesetservice|ddesett|ddesettopic|ddet|ddeterminate|date)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(datet|datetime|day|dbc|dbf|defa|defaultext|dele|deleted|desc|descending|diff|difference|dire|directory|disk)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(diskspace|disp|displaypath|dmy|dode|dodefault|dow|driv|drivetype|drop|dropoffline|dtoc|dtor|dtos|dtot|edit)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(editsource|empt|empty|endfor|endscan|eof|erro|error|eval|evaluate|event|eventhandler|evl|exec|execscript|exp|fchs|fchsize)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(fclo|fclose|fcou|fcount|fcre|fcreate|fdat|fdate|feof|ferr|ferror|fflu|fflush|fget|fgets|fiel|field|file|filet)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(filetostr|filt|filter|fkla|fklabel|fkma|fkmax|floc|flock|floo|floor|font|fontmetric|fope|fopen|for|forc)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(forceext|forcep|forcepath|foun|found|fput|fputs|frea|fread|fsee|fseek|fsiz|fsize|ftim|ftime|full|fullpath)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(fv|fwri|fwrite|geta|getautoincvalue|getcp|getc|getcolor|getcu|getcursoradapter|getd|getdir|gete|getenv)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(getf|getfile|getfl|getfldstate|getfo|getfont|geth|gethost|geti|getinterface|getn|getnextmodified|geto)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(getobject|getp|getpem|getpi|getpict|getpr|getprinter|getr|getresultset|getwordc|getwordcount|getwordn)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(getwordnum|getb|getbar|getpa|getpad|gomo|gomonth|head|header|home|hour|icas|icase|imes|imestatus|id)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(idxc|idxcollate|iif|inli|inlist|indb|indbc|inde|indexseek|inke|inkey|inpu|inputbox|insm|insmode|int)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(isal|isalpha|isbl|isblank|isco|iscolor|isdi|isdigit|isex|isexclusive|isfl|isflocked|isho|ishosted)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(isle|isleadbyte|islo|islower|isme|ismemofetched|ismo|ismouse|isnu|isnull|ispe|ispen|isrl|isrlocked)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(isre|isreadonly|istr|istransactable|isup|isupper|justd|justdrive|juste|justext|justf|justfname)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(justp|justpath|justs|juststem|key|keym|keymatch|last|lastkey|left|leftc|len|lenc|like|likec|line)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(lineno|load|loadpicture|locf|locfile|lock|log|log1|log10|look|lookup|lowe|lower|ltri|ltrim|lupd)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(lupdate|make|maketransactable|max|mcol|mdow|mdown|mdx|mdy|meml|memlines|memo|memory|menu|mess)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(message|messageb|messagebox|msgb|messagebox|min|minu|minute|mlin|mline|mod|mont|month|mrkb)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(mrkbar|mrkp|mrkpad|mrow|mton|mwin|mwindow|ndx|new|newobject|newo|newobject|norm|normalize|ntom)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(numl|numlock|nvl|objt|objtoclient|occu|occurs|oldv|oldval|on|orde|order|os|pad|padc|padl|padr)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(para|parameters|paym|payment|pcol|pcou|pcount|pems|pemstatus|pi|popu|popup|prim|primary|prin)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(printstatus|prmb|prmbar|prmp|prmpad|prog|program|prom|prompt|prop|proper|prow|prti|prtinfo)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(putf|putfile|pv|quar|quarter|rais|raiseevent|rand|rat|ratc|ratl|ratline|recc|reccount|recn)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(recno|recs|recsize|refr|refresh|rela|relation|remo|removeproperty|repl|replicate|requ|requery)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(rgb|rgbs|rgbscheme|righ|right|rightc|rloc|rlock|roun|round|rtod|rtri|rtrim|sqlca|sqlcancel)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(sqlcol|sqlcolumns|sqlcom|sqlcommit|sqlcon|sqlconnect|sqld|sqldisconnect|sqle|sqlexec|sqlg|sqlgetprop)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(sqli|sqlidledisconnect|sqlm|sqlmoreresults|sqlp|sqlprepare|sqlr|sqlrollback|sqlse|sqlsetprop|sqlst)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(sqlstringconnect|sqlt|sqltables|save|savepicture|scan|sche|scheme|scol|scols|sec|seco|seconds|seek|sele)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(select|set|setf|setfldstate|setr|setresultset|sign|sin|skpb|skpbar|skpp|skppad|soun|soundex|spac)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(space|sqrt|srow|srows|str|stre|strextract|strto|strtofile|strc|strconv|strtr|strtran|stuf|stuff)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(stuffc|subs|substr|substrc|sum|sys|sysm|sysmetric|tabler|tablerevert|tableu|tableupdate|tag|tagc)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(tagcount|tagn|tagno|tan|targ|target|text|textmerge|time|tran|transform|trim|ttoc|ttod|txnl|txnlevel)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(txtw|txtwidth|type|unbi|unbindevents|uppe|upper|used|val|vart|vartype|vers|version|wdoc|wdockable)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(wbor|wborder|wchi|wchild|wcol|wcols|week|wexi|wexist|wfon|wfont|wlas|wlast|wlco|wlcol|wlro|wlrow)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(wmax|wmaximum|wmin|wminimum|wont|wontop|wout|woutput|wpar|wparent|wrow|wrows|wtit|wtitle|wvis|wvisible)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(xmlt|xmltocursor|xmlu|xmlupdategram|year|acti|activate|add|alte|alter|appe|append|asse|assert|aver)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(average|begi|begin|blan|brow|browse|buil|build|calc|calculate|canc|cancel|catc|catch|cd|chdi)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(chdir|chan|change|clea|clear|clos|close|comp|compile|cont|continue|copy|coun|count|crea|create|deac)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(deactivate|debu|debug|debugo|debugout|decl|declare|defi|dele|dime|dimension|dir|disp|display|do|dock)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(doev|doevents|dotip|drop|edit|ejec|eject|end|endc|endcase|endde|enddo|endfo|endfu|endi|endpri)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(endprintjob|endp|ends|endt|endtr|endw|eras|erase|erro|exit|expo|export|exte|external|fina|flus|flush)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(func|gath|gather|gete|getexpr|go|goto|help|hidd|hide|impl|impo|import|inde|index|inse|keyb|keyboard)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(labe|list|local|loca|locate|loop|lpar|md|mkdi|modi|modify|mous|mouse|move|node|nodefault|note|open)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(opendatatip|othe|otherwise|pack|para|parameters|play|pop|prin|printjob|priv|private|prot|publ)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(public|push|quit|rd|read|reca|recall|rein|reindex|rele|release|remo|remove|rena|rename|repl|replace)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(arepltip|repo|restore|resu|resume|retr|retry|retu|rmdi|roll|rollback|run|scat|scatter|seek|sele|sort)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(stor|store|sum|susp|suspend|thro|throw|tota|total|unlo|unlock|upda|use|usetip|vali|validate|wait|zap)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(additive|after|alias|all|alt|alternate|american|ansi|app|array|as|asc|ascending|asserts|at|auto|autoinc)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(autoincerror|automatic|autosave|bar|before|bell|binary|blank|blocksize|bottom|british|browseime|by)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(candidate|carry|cdx|center|century|cga|character|check|class|classlib|click|clock|codepage|collate)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(collection|color|column|command|compact|compatible|confirm|connection|connections|connstring|console)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(control|coverage|cpcompile|cpdialog|csv|currency|cursor|data|database|databases|datasession|datasource)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(date|dbf|dblclick|decimals|default|delete|deleted|deletetables|delimited|delimiters|desc|descending)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(development|device|dif|directory|distinct|dll|dlls|dmy|dohistory|dos|double|drag|each|echo|encrypt)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(enginebehavior|environment|error|escape|eventlist|eventtracking|exact|except|exclude|exclusive|exe)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(extended|fdow|field|fields|file|files|fill|filter|finally|fixed|flags|float|font|footer|force|foreign)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(form|format|foxplus|free|freeze|french|from|full|fullpath|fweek|general|group|grow|halfheight|having)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(heading|headings|helpfilter|hidden|hours|icon|id|implements|in|indexes|inner|insert|into|italian|japan)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(join|key|keycomp|label|last|ledit|left|library|like|line|link|lock|logerrors|long|lparameters|lpartition)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(ltrjustify|macdesktop|mackey|macro|macros|margin|mark|master|max|mdi|mdy|memo|memory|memowidth|memvar|menu)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(menus|message|method|middle|min|minimize|mkdir|mod|mover|mru|mtdll|multilocks|multiselect|name|near|negotiate)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(next|nextvalue|noappend|nocaptions|noclear|noclose|noconsole|nocptrans|nodebug|nodelete|nodialog|nodup|noedit)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(noenvironment|nofilter|nofloat|nogrow|noinit|nolgrid|nolink|nomargin|nomdi|nomenu|nominimize|nomodify|none)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(nooptimize|nooverwrite|nopageeject|noprompt|norefresh|norequery|noreset|norgrid|norm|normal|nosave|noshow)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(notify|nowait|nowindow|nozoom|null|nulldisplay|object|objects|odometer|of|off|oleobject|on|optimize|order|pad)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(page|palette|panel|partition|password|path|pdox|pdsetup|percent|pictres|picture|pixels|plain|point|popup|popups)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(position|preference|pretext|preview|primary|printer|production|project|prompt|protected|query|range)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(readborder|readwrite|recompile|record|recover|recycle|redit|reference|references|refresh|relation|relative|remote)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(report|reportbehavior|reprocess|resource|resources|rest|return|right|rmdir|rollover|rpd|rtljustify|safety|same|save)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(scheme|screen|scroll|sdf|seconds|select|selection|separator|set|share|sheet|shift|short|shortcut|show|shutdown|size)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(skip|space|sql|sqlbuffering|status|step|strictdate|structure|style|summary|sylk|sysformats|sysmenu|system|tab|table)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(tables|tablevalidate|tag|taiwan|talk|textmerge|time|timeout|title|to|top|topic|transaction|try|endtry|trbetween|trigger|type)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(typeahead|udfparms|union|unique|update|usa|userid|valid|value|values|varcharmapping|view|views|when|where|while)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(endtext|define|class|enddefine|endproc|include|func|function|endfunc)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(awidth|window|windows|wks|wrap|wrk|xls|ymd|zoom|and|or|not)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(this|thisform)\b)</string>
			<key>name</key>
			<string>keyword.foxpro</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>classDefinition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.vbnet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.vbnet</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:\b(define class)\s+([a-zA-Z_]\w*)\s*)</string>
			<key>name</key>
			<string>meta.class.foxpro</string>
		</dict>
		<key>comment1</key>
		<dict>
			<key>match</key>
			<string>(&amp;&amp;.*)</string>
			<key>name</key>
			<string>comment.foxpro</string>
		</dict>
		<key>comment2</key>
		<dict>
			<key>match</key>
			<string>(^\s*\*.*)</string>
			<key>name</key>
			<string>comment.foxpro</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>(?i:(\.t\.|\.f\.|\.null\.))</string>
			<key>name</key>
			<string>constant.foxpro</string>
		</dict>
		<key>controlKeywords</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(if|else|endif|with|endwith|do case|case|endcase|)\b)</string>
			<key>name</key>
			<string>keyword.control.foxpro</string>
		</dict>
		<key>functionDefinition</key>
		<dict>
			<key>begin</key>
			<string>(?i:\b(proc[e]?[d]?[u]?[r]?[e]?|func[t]?[i]?[o]?[n]?)\s+([a-zA-Z_]\w*)\s*(\()?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.function.vbnet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.vbnet</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.parameters.vbnet</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.vbnet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))?\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.vbnet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.vbnet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#otherKeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#supportTypes</string>
				</dict>
			</array>
		</dict>
		<key>numericConstant</key>
		<dict>
			<key>match</key>
			<string>\b(-?\d+(\.?\d?)*)</string>
			<key>name</key>
			<string>constant.foxpro</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>\b(\+|\-|\^|\*|\=)\b</string>
			<key>name</key>
			<string>keyword.operator.foxpro</string>
		</dict>
		<key>string1</key>
		<dict>
			<key>match</key>
			<string>(")(.*)(")</string>
			<key>name</key>
			<string>string.foxpro</string>
		</dict>
		<key>string2</key>
		<dict>
			<key>match</key>
			<string>(')(.*)(')</string>
			<key>name</key>
			<string>string.foxpro</string>
		</dict>
		<key>string3</key>
		<dict>
			<key>match</key>
			<string>(\[)(.*)(\])</string>
			<key>name</key>
			<string>string.foxpro</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>.foxpro</string>
	<key>uuid</key>
	<string>e42126eb-466c-4187-9bd2-5385285fbe69</string>
</dict>
</plist>
