<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gradle</string>
	</array>
	<key>name</key>
	<string>Gradle Build Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#gradle</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?!&lt;project\.)(\w+)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.block.groovy.gradle</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.definition.block.groovy.gradle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#gradle-groovy</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>gradle</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tasks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.groovy</string>
				</dict>
			</array>
		</dict>
		<key>gradle-groovy</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.groovy</string>
				</dict>
			</array>
		</dict>
		<key>tasks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>task\s+(\w+)\s*(?=[\({])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.task.groovy.gradle</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^</string>
					<key>name</key>
					<string>meta.definition.task.groovy.gradle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#gradle-groovy</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.groovy.gradle</string>
	<key>uuid</key>
	<string>D7E70EBB-ED68-4F09-A5AF-9126624AE319</string>
</dict>
</plist>
