<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>atg</string>
	</array>
	<key>name</key>
	<string>Coco/R</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(ANY|CHARACTERS|COMMENTS|COMPILER|CONTEXT|END|FROM|IF|IGNORE|IGNORECASE|NESTED|PRAGMAS|PRODUCTIONS|SYNC|TOKENS|TO|WEAK)\b</string>
			<key>name</key>
			<string>keyword.source.cocor</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"(\\.|[^\\"])*"</string>
			<key>name</key>
			<string>string.quoted.double.source.cocor</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'(\\.|[^\\"])*?'</string>
			<key>name</key>
			<string>constant.character.source.cocor</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\.</string>
			<key>end</key>
			<string>\.\)</string>
			<key>name</key>
			<string>source.cocor</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.*?</string>
					<key>name</key>
					<string>variable.parameter.source.cocor</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>source.cocor</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.*?</string>
					<key>name</key>
					<string>variable.parameter.source.cocor</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>=|\(|\)|\{|\}|\[|\]|\|</string>
			<key>name</key>
			<string>constant.language.source.cocor</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n</string>
			<key>name</key>
			<string>comment.line.double-dash.source.cocor</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.cocor</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cocor</string>
	<key>uuid</key>
	<string>e1a5da4e-ed93-447d-b111-a70a1ebe3071</string>
</dict>
</plist>
