// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TextmateBundleInstaller
{
    static class Vsix
    {
        public const string Id = "4773ce75-6f30-4269-9557-1f7c30a47be2";
        public const string Name = "Syntax Highlighting Pack";
        public const string Description = @"Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...";
        public const string Language = "en-US";
        public const string Version = "1.4";
        public const string Author = "Mads Kristensen";
        public const string Tags = "bat, clojure, go, goovy, ini, jade, java, javadoc, lua, make, perl, php, ruby, rust, bash, swift";
    }
}
