// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.179
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TextmateBundleInstaller
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackageString = "13bea213-be01-48dc-a51e-7d148c7bec69";
        public const string guidVSPackageCmdSetString = "69ac85de-faa0-4e5a-b7c0-d3bfe76312cf";
        public static Guid guidVSPackage = new Guid(guidVSPackageString);
        public static Guid guidVSPackageCmdSet = new Guid(guidVSPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ReportMissingLanguage = 0x0100;
    }
}
